<?php

/**
 * Implements hook_theme().
 */
function wisetalent_user_theme($existing, $type, $theme, $path) :array
{
  return [
    'login' => [
      'render element' => 'elements',
      'variables' => [
        'content' => NULL
      ],
    ],
    'register' => [
      'render element' => 'elements',
      'variables' => [
        'content' => NULL
      ],
    ],
    'forgot_password' => [
      'render element' => 'elements',
      'variables' => [
        'content' => NULL
      ],
    ],

  ];
}


use Drupal\user\UserInterface;


 function wisetalent_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    // Modifier le formulaire.
    $form['#prefix'] = '<div class="form-group mb3">';

    $form['name'] = [
      '#type' => 'textfield',
      //'#title' => $this->t('Username'),
      '#size' => 60,
      '#maxlength' => UserInterface::USERNAME_MAX_LENGTH,
      '#required' => TRUE,
      '#id'=>'name',
      '#attributes' => [
        'placeholder' => 'Nom utilisateur *' ,
        'class' => ['form-control'],
        'required' => 'required',
      ],
    ];
    $form['pass'] = [
      '#type' => 'password',
      '#id'=>'password',
      //'#title' => $this->t('Password'),
      '#size' => 60,
      '#required' => TRUE,
      '#attributes' => [
        'placeholder' => '********' ,
        'class' => ['form-control'],
      ],
    ];
    $form['actions'] = [
      '#type' => 'actions',
      '#prefix' => '<div class="col-md-12">',
      '#suffix' => '</div>',
    ];
    $form['actions']['submit'] = [
      '#type' => 'submit',
      '#value' => 'Connexion',
      '#attributes'=>[
        'class' => ['site-button']
      ]
    ];
    $form['#suffix'] = '</div>';
  }
  return $form;
}

