<?php

/**
 * Implements hook_theme().
 */
function wisetalent_user_theme($existing, $type, $theme, $path) :array
{
  return [
    'login' => [
      'render element' => 'elements',
      'variables' => [
        'content' => NULL
      ],
    ],
    'register' => [
      'render element' => 'elements',
      'variables' => [
        'content' => NULL
      ],
    ],
    'forgot_password' => [
      'render element' => 'elements',
      'variables' => [
        'content' => NULL
      ],
    ],
    'profile_sidebar' => [
      'render element' => 'elements',
      'variables' => [
        'content' => NULL
      ],
    ],

  ];
}


use Drupal\user\Entity\User;
use Drupal\user\UserInterface;


 function wisetalent_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    // Modifier le formulaire.
    $form['#prefix'] = '<div class="form-group mb3">';

    $form['name'] = [
      '#type' => 'textfield',
      //'#title' => $this->t('Username'),
      '#size' => 60,
      '#maxlength' => UserInterface::USERNAME_MAX_LENGTH,
      '#required' => TRUE,
      '#id'=>'name',
      '#attributes' => [
        'placeholder' => 'Nom utilisateur *' ,
        'class' => ['form-control'],
        'required' => 'required',
      ],
    ];
    $form['pass'] = [
      '#type' => 'password',
      '#id'=>'password',
      //'#title' => $this->t('Password'),
      '#size' => 60,
      '#required' => TRUE,
      '#attributes' => [
        'placeholder' => '********' ,
        'class' => ['form-control'],
      ],
    ];
    $form['actions'] = [
      '#type' => 'actions',
      '#prefix' => '<div class="col-md-12">',
      '#suffix' => '</div>',
    ];
    $form['actions']['submit'] = [
      '#type' => 'submit',
      '#value' => 'Connexion',
      '#attributes'=>[
        'class' => ['site-button']
      ]
    ];
    $form['#suffix'] = '</div>';
  }
   $user = \Drupal::currentUser();
   $user = User::load($user->id());
   $profil = $user->field_profils->value;

   if($form_id == 'user_form'){
     switch ($profil){
       case 'candidat':
         unset($form['field_nombre_employee']);
         unset($form['field_raison_social']);
         unset($form['field_situation_geographique']);
         unset($form['field_telephone']);
         $form['field_nom_prenoms']['widget'][0]['value']['#required'] = TRUE;
         $form['field_niveau_scolaire']['widget']['#required'] = TRUE;
         $form['field_contact_whatsapp']['widget'][0]['value']['#required'] = TRUE;

         break;
       case 'entreprise'||'employeur':
         unset($form['field_nom_prenoms']);
         unset($form['field_niveau_scolaire']);
         unset($form['field_contact_whatsapp']);
         $form['field_nombre_employee']['widget']['#required'] = TRUE;

         $form['field_raison_social']['widget'][0]['value']['#required'] = TRUE;
         $form['field_situation_geographique']['widget'][0]['value']['#required'] = TRUE;
         $form['field_telephone']['widget'][0]['value']['#required'] = TRUE;
         break;
       case 'freelance':
         unset($form['field_nombre_employee']);
         unset($form['field_raison_social']);
         unset($form['field_situation_geographique']);
         unset($form['field_telephone']);
         $form['field_nom_prenoms']['widget'][0]['value']['#required'] = TRUE;
         $form['field_niveau_scolaire']['widget']['#required'] = TRUE;
         $form['field_contact_whatsapp']['widget'][0]['value']['#required'] = TRUE;
         break;
     }
/*
     $form['actions'] = [
       '#type' => 'actions',
       '#prefix' => '<div class="col-md-12">',
       '#suffix' => '</div>',
     ];
     $form['actions']['submit'] = [
       '#type' => 'submit',
       '#value' => t('Save'),
       '#attributes'=>[
         'class' => ['site-button']
       ]
     ];
*/
     //dump($form);
     //$form['#suffix'] = '</div>';
   }

  return $form;
}



