<?php

declare(strict_types=1);

/**
 * @file
 * Functions to support theming in the wiseTalent theme.
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function wisetalent_preprocess_html(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function wisetalent_preprocess_user(&$variables) {
  $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  if ($user && !$user->user_picture->isEmpty()) {
    $uri = $user->user_picture->entity->getFileUri();
    $user_display_image = \Drupal::service('file_url_generator')->generateAbsoluteString($uri);

    $style = \Drupal\image\Entity\ImageStyle::load('thumbnail');
    $image_uri = $style->buildUri($uri);
    $user_small_image = \Drupal::service('file_url_generator')->generateAbsoluteString($image_uri);
  } else {
    $user_display_image = '';
    $user_small_image = '';
  }
  $variables['user_display_image'] = $user_display_image;
  $variables['user_small_image'] = $user_small_image;
  $variables['current_user'] = $user->getAccountName();

}
/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function wisetalent_preprocess_node(array &$variables): void {

}


